resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

resources:
- name: dp-nlp-category-api
  type: pull-request
  check_every: 1m
  webhook_token: ((webhook-token))
  source:
    repository: flaxandteal/onyx-dp-nlp-category-api
    access_token: ((github-access-token))

jobs:
- name: lint
  public: true
  plan:
  - get: dp-nlp-category-api
    trigger: true
    version: every
  - put: dp-nlp-category-api
    params:
      path: dp-nlp-category-api
      status: pending
  - task: running-linting-process
    file: dp-nlp-category-api/ci/lint.yml
    on_failure:
      put: dp-nlp-category-api
      params:
        path: dp-nlp-category-api
        status: failure
  - put: dp-nlp-category-api
    params:
      path: dp-nlp-category-api
      status: success

- name: unit-testing
  public: true
  plan:
  - get: dp-nlp-category-api
    trigger: true
    version: every
  - put: dp-nlp-category-api
    params:
      path: dp-nlp-category-api
      status: pending
  - task: running-unit-tests
    file: dp-nlp-category-api/ci/unit.yml
    on_failure:
      put: dp-nlp-category-api
      params:
        path: dp-nlp-category-api
        status: failure
  - put: dp-nlp-category-api
    params:
      path: dp-nlp-category-api
      status: success

- name: component-testing
  public: true
  plan:
  - get: dp-nlp-category-api
    trigger: true
    version: every
  - put: dp-nlp-category-api
    params:
      path: dp-nlp-category-api
      status: pending
  - task: running-component-tests
    file: dp-nlp-category-api/ci/component.yml
    on_failure:
      put: dp-nlp-category-api
      params:
        path: dp-nlp-category-api
        status: failure
  - put: dp-nlp-category-api
    params:
      path: dp-nlp-category-api
      status: success
      
- name: build
  public: true
  plan:
  - get: dp-nlp-category-api
    trigger: true
    version: every
  - put: dp-nlp-category-api
    params:
      path: dp-nlp-category-api
      status: pending
  - task: build
    file: dp-nlp-category-api/ci/build.yml
    on_failure:
      put: dp-nlp-category-api
      params:
        path: dp-nlp-category-api
        status: failure
  - put: dp-nlp-category-api
    params:
      path: dp-nlp-category-api
      status: success
