resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

resources:
- name: dp-nlp-search-scrubber
  type: pull-request
  check_every: 5m
  webhook_token: ((webhook-token))
  source:
    repository: flaxandteal/onyx-dp-search-scrubber-api
    access_token: ((github-access-token))
    
- name: scrubber-docker-repo
  type: registry-image
  icon: docker
  source:
    repository: flaxandteal/scrubber-api
    username: ((username))
    password: ((password))
    tag: latest

jobs:
- name: validation
  public: true
  plan:
  - get: dp-nlp-search-scrubber
    trigger: true
    version: every
  - put: dp-nlp-search-scrubber
    params:
      path: dp-nlp-search-scrubber
      status: pending
  - in_parallel:
    - task: audit
      file: dp-nlp-search-scrubber/ci/audit.yml
      on_failure:
        put: dp-nlp-search-scrubber
        params:
          path: dp-nlp-search-scrubber
          status: "failed audit process"
    - task: lint
      file: dp-nlp-search-scrubber/ci/lint.yml
      on_failure:
        put: dp-nlp-search-scrubber
        params:
          path: dp-nlp-search-scrubber
          status: "failed linting process"
    - task: unit-testing
      file: dp-nlp-search-scrubber/ci/unit.yml
      on_failure:
        put: dp-nlp-search-scrubber
        params:
          path: dp-nlp-search-scrubber
          status: "failed unit testing"
    - task: component-testing
      file: dp-nlp-search-scrubber/ci/component.yml
      on_failure:
        put: dp-nlp-search-scrubber
        params:
          path: dp-nlp-search-scrubber
          status: "failed component testing"

- name: build-and-deploy
  plan:
  - get: dp-nlp-search-scrubber
    trigger: true
    version: every
    passed: [validation]
  - task: build
    file: dp-nlp-search-scrubber/ci/build.yml
  - task: deploy
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: build
      outputs:
      - name: image
      params:
        CONTEXT: build/
        DOCKERFILE: build/Dockerfile.concourse
      run:
        path: build
  - put: scrubber-docker-repo
    params:
      image: image/image.tar