resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

resources:
- name: dp-nlp-berlin-api
  type: pull-request
  check_every: 1m
  webhook_token: ((webhook-token))
  source:
    repository: flaxandteal/onyx-dp-nlp-berlin-api
    access_token: ((github-access-token))

- name: berlin-api
  type: registry-image
  icon: docker
  source:
    repository: flaxandteal/berlin_api
    username: ((username))
    password: ((password))
    tag: latest

jobs:
- name: validation
  public: true
  plan:
  - get: dp-nlp-berlin-api
    trigger: true
    version: every
  - put: dp-nlp-berlin-api
    params:
      path: dp-nlp-berlin-api
      status: pending
  - in_parallel:
    - task: audit
      file: dp-nlp-berlin-api/ci/audit.yml
      on_failure:
        put: dp-nlp-berlin-api
        params:
          path: dp-nlp-berlin-api
          status: "failed auditing process"
    - task: lint
      file: dp-nlp-berlin-api/ci/lint.yml
      on_failure:
        put: dp-nlp-berlin-api
        params:
          path: dp-nlp-berlin-api
          status: "failed linting process"
    - task: unit-testing
      file: dp-nlp-berlin-api/ci/unit.yml
      on_failure:
        put: dp-nlp-berlin-api
        params:
          path: dp-nlp-berlin-api
          status: "failed unit testing"
    - task: component-testing
      file: dp-nlp-berlin-api/ci/component.yml
      on_failure:
        put: dp-nlp-berlin-api
        params:
          path: dp-nlp-berlin-api
          status: "failed component testing"

- name: build-and-push
  plan:
  - get: dp-nlp-berlin-api
    trigger: true
    version: every
    passed: [validation]
  - task: build-task-image
    privileged: true
    file: dp-nlp-berlin-api/ci/build.yml
  - put: berlin-api
    params:
      image: image/image.tar
